version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "uv"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: "django"
        versions: [">=6.0.0"]
      - dependency-name: "stripe"
        versions: [">=11.4.0"]
      # Ignore all setuptools updates; issue is not version-specific.
      # Can be removed once Dependabot handles no-op uv updates.
      - dependency-name: "setuptools"

  - package-ecosystem: "npm"
    directory: "/app/eventyay/webapp/video"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/app/eventyay/webapp/schedule"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/app/eventyay/webapp/schedule-editor"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
