# Generated by Django 5.2.12 on 2026-06-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0031_migrate_meta_noindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="etherpad_url",
            field=models.URLField(
                blank=True,
                help_text="Collaborative notes pad for this session. Notes are hosted on the configured Etherpad instance.",
                max_length=500,
                null=True,
                verbose_name="Etherpad URL",
            ),
        ),
    ]
