# Generated by Django 5.2.15 on 2026-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_device_checkin_lists_and_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='force_hide_speaker_emails',
            field=models.BooleanField(default=False, help_text='When enabled, reviewers will not be able to see speaker email addresses, but can still see other speaker details.', verbose_name='Hide speaker emails only'),
        ),
        migrations.AlterField(
            model_name='team',
            name='force_hide_speaker_names',
            field=models.BooleanField(default=False, help_text='Normally, anonymisation is configured in the event review settings. This setting will <strong>override the event settings</strong> and always hide all speaker details for this team.', verbose_name='Hide all speaker details'),
        ),
        migrations.AlterField(
            model_name='team',
            name='limit_tracks',
            field=models.ManyToManyField(blank=True, help_text='Restrict this team’s access to proposals, sessions, reviews, speakers, and schedule data for the selected tracks only. Leave empty for access to all tracks in the team’s events.', to='base.track', verbose_name='Limit to tracks'),
        ),
    ]
