# Generated by Django 5.2.15 on 2026-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_make_event_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_change_exhibition_proposals',
            field=models.BooleanField(default=False, help_text='Can review proposals and approve or reject exhibitor and sponsor applications. This provides full proposal-management permissions beyond standard reviewing, without granting access to the rest of the event setup.', verbose_name='Reviewer Manager — can review and manage exhibitor proposals'),
        ),
        migrations.AddField(
            model_name='team',
            name='hide_exhibition_applicant_emails',
            field=models.BooleanField(default=False, help_text='When enabled, Exhibitor Reviewers on this team cannot see the email addresses of proposal applicants, but can still review the rest of the proposal.', verbose_name='Hide emails of applicants'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_exhibition_reviewer',
            field=models.BooleanField(default=False, help_text='Can review and provide feedback on exhibitor and sponsor proposals but cannot approve, reject, or otherwise manage them.', verbose_name='Exhibitor Reviewer — can only review exhibitor proposals'),
        ),
    ]
