# Generated by Django 5.2.15 on 2026-07-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_team_can_manage_bank_transfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_publicly',
            field=models.BooleanField(default=False),
        ),
    ]
