name: eventyay-next

services:
  web:
    image: eventyay/eventyay-next:${TAG}
    container_name: eventyay-next-web
    command: gunicorn eventyay.config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120 --graceful-timeout 90
    volumes:
      - ${DATA_DIR:-./data}/static:/home/app/web/eventyay/static.dist
      - ${DATA_DIR:-./data}/data:/home/app/web/eventyay/data
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  websocket:
    image: eventyay/eventyay-next:${TAG}
    container_name: eventyay-next-websocket
    entrypoint: daphne -b 0.0.0.0 -p 8001 eventyay.config.asgi:application
    volumes:
      - ${DATA_DIR:-./data}/static:/home/app/web/eventyay/static.dist
      - ${DATA_DIR:-./data}/data:/home/app/web/eventyay/data
    ports:
      - 8001:8001
    expose:
      - 8001
    env_file:
      - ./.env
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    depends_on:
      - db
      - redis

  worker:
    image: eventyay/eventyay-next:${TAG}
    container_name: eventyay-next-worker
    entrypoint: celery -A eventyay worker -l info
    volumes:
      - ${DATA_DIR:-./data}/static:/home/app/web/eventyay/static.dist
      - ${DATA_DIR:-./data}/data:/home/app/web/eventyay/data
    env_file:
      - ./.env
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    depends_on:
      - db
      - redis

  beat:
    image: eventyay/eventyay-next:${TAG}
    container_name: eventyay-next-beat
    entrypoint: celery -A eventyay beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ${DATA_DIR:-./data}/static:/home/app/web/eventyay/static.dist
      - ${DATA_DIR:-./data}/data:/home/app/web/eventyay/data
    env_file:
      - ./.env
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: eventyay-next-db
    volumes:
      - ${DATA_DIR:-./data}/postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: eventyay-next-redis
    restart: unless-stopped
    volumes:
      - rd:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  watchtower:
    image: nickfedor/watchtower
    container_name: eventyay-next-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      WATCHTOWER_NOTIFICATIONS: 'shoutrrr'
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${WATCHTOWER_NOTIFICATIONS_HOSTNAME}
      WATCHTOWER_POLL_INTERVAL: 600
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL}
    command: watchtower eventyay-next-watchtower eventyay-next-web eventyay-next-websocket eventyay-next-worker eventyay-next-beat --cleanup

volumes:
  rd:
