# Generated by Django 5.2 on 2026-04-25
# Add scheduled_at field to EmailQueue for email scheduling feature

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='scheduled_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='If set, the email will be sent at this time instead of immediately.',
                null=True,
            ),
        ),
    ]
