# Generated by Django 5.2.12 on 2026-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badgevoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgelayout',
            name='allow_badge_editing',
            field=models.BooleanField(
                default=False,
                verbose_name='Allow badge editing',
            ),
        ),
    ]
